# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9f90291de7dc292b2dfbffb6bcf05b3e"
name = "order-forms-ext"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "face-reality-pro-app-test-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false
